name: Android CI

on:
  push:
    branches:
      -main
  pull_request:
    branches:
      - main
      - "feature/**"


jobs:
  build:

    runs-on: ubuntu-latest
    environment: TestUser
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      - name: Add secrets to local properties
        run: |
          touch local.properties
          echo "test_user=${{ secrets.TEST_USER }}" > local.properties
          echo "test_password=${{ secrets.TEST_PASSWORD }}" >> local.properties
      - name: Run linter
        run: ./gradlew lint
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
  test:
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'
          cache: 'gradle'
      - name: Touch local properties
        run: touch local.properties
      - name: Run unit tests
        uses: ReactiveCircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: google_apis
          arch: x86_64
          script: |
            pwd
            ls -a
            ./gradlew test
  checkstyle:
    name: runner / checkstyle
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dbelyaev/action-checkstyle@master
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          level: warning